### ISSUE TITLE
Do you have a malicious sample of APT?

### ISSUE THREAD

**Issue by Allenxiaokang** [CyberMonitor/APT_CyberCriminal_Campagin_Collections#3]
I am currently working on malicious code analysis,And collecting a large number of APT malicious samples

**Comment by pedroliveira95** [comment]
Maybe sharing the one you are holding now would be a good start in order to motivate people to provide for you, eye for an eye don't be greedy start your public repo.

**Comment by hgascon** [comment]
@Allenxiaokang I am doing the same, maybe we compare our data and share it. Ping me if you are interested.

**Comment by hgascon** [comment]
@pedroliveira95 any public repo of samples you are aware about?

**Comment by pedroliveira95** [comment]
This is one the biggest as far as i know, i still didn't took time looking into it, because right know i'm focused on other issue and i'm still to raw in the field, but other one i saw was https://github.com/ytisf/theZoo. Though the best way to do it is find interest in a particular attack and search it's source code, you won't have time to search for them all, if the point of collection is for data collection for future software development, which i doubt else you wouldn't be here, than i can't really help. So mainly find interest in a particular one and do upside down research in it.

**Comment by CyberMonitor** [comment]
Hi All, 
   basically, I got the APT samples from hashs of APT report via VirusShare(https://virusshare.com/). 
   I am not sure is it a good way to put samples using git.  :)   let me trying...

**Comment by hgascon** [comment]
I think github quota is 1Gb. Alternatively, you can use google drive (15Gb) or other repository for large files and then commit only the links to the files.
